security:
    providers:
        db_provider:
            entity:
                class: App\Entity\User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: ~
            http_basic: ~
            provider: db_provider
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_READER: ROLE_USER
        ROLE_LIBRARIAN: ROLE_READER
        ROLE_ADMIN: ROLE_LIBRARIAN
