register:
    path: /register
    controller: App\Controller\RegistrationController::register
login:
    path: /login
    controller: App\Controller\security\SecurityController::login
logout:
    path: /logout
show-profile:
    path: /user/profile
    controller: App\Controller\user\UserController::showProfile
edit-profile:
    path: /user/profile/edit
    controller: App\Controller\user\UserController::editProfile
show-activity:
    path: /user/activity
    controller: App\Controller\user\UserController::showActivity
show-notifications:
    path: /user/notifications
    controller: App\Controller\user\UserController::showNotifications
index:
    path: /
    controller: App\Controller\DefaultController::index
show-catalog:
    path: /catalog/books/{page}
    controller: App\Controller\catalog\CatalogController::showCatalog
    defaults:
        page: 1
    requirements:
        page: '\d+'
show-books-by-author:
    path: /catalog/books-by-author/{id}/{page}
    controller: App\Controller\catalog\CatalogController::showAuthorCatalog
    defaults:
        id: 1
        page: 1
    requirements:
        id: '\d+'
        page: '\d+'
show-books-by-genre:
    path: /catalog/books-by-genre/{id}/{page}
    controller: App\Controller\catalog\CatalogController::showGenreCatalog
    defaults:
        id: 1
        page: 1
    requirements:
        id: '\d+'
        page: '\d+'
show-book:
    path: /catalog/book/{id}
    controller: App\Controller\catalog\BookController::showBook
    defaults:
        id: 1
    requirements:
        id: '\d+'
show-author:
    path: /catalog/author/{id}
    controller: App\Controller\catalog\AuthorController::showAuthor
    defaults:
        id: 1
    requirements:
        id: '\d+'
reserve-book:
    path: /catalog/book/{id}/reserve
    controller: App\Controller\reader\LibraryController::reserveBook
    defaults:
        id: 1
    requirements:
        id: '\d+'
toggle-favorite:
    path: /catalog/book/{id}/toggle-favorite
    controller: App\Controller\user\UserController::toggleFavorite
    requirements:
        id: '\d+'
new-book:
    path: /catalog/books/new
    controller: App\Controller\librarian\LibraryController::newBook
edit-book:
    path: /catalog/book/{id}/edit
    controller: App\Controller\librarian\LibraryController::editBook
    requirements:
        id: '\d+'
delete-book:
    path: /catalog/book/{id}/delete
    controller: App\Controller\librarian\LibraryController::deleteBook
    requirements:
        id: '\d+'
new-author:
    path: /catalog/authors/new
    controller: App\Controller\librarian\LibraryController::newAuthor
edit-author:
    path: /catalog/author/{id}/edit
    controller: App\Controller\librarian\LibraryController::editAuthor
    requirements:
        id: '\d+'
delete-author:
    path: /catalog/author/{id}/delete
    controller: App\Controller\librarian\LibraryController::deleteAuthor
    requirements:
        id: '\d+'
new-genre:
    path: /catalog/genres/new
    controller: App\Controller\librarian\LibraryController::newGenre
show-reservations:
    path: /reservations
    controller: App\Controller\librarian\LibraryController::showReservations
update-reservation:
    path: /reservations/update/{id}/{status}
    controller: App\Controller\librarian\LibraryController::updateReservationStatus
    methods: [GET]
    defaults:
        id: 1
        status: 'reserved'
    requirements:
        id: '\d+'
show-readers:
    path: /readers
    controller: App\Controller\librarian\LibraryController::showReaders
show-users:
    path: /admin/users
    controller: App\Controller\admin\AdminController::showAllUsers
delete-user:
    path: /admin/users/{id}/delete
    controller: App\Controller\admin\AdminController::deleteUser
    requirements:
        id: '\d+'
edit-user:
    path: /admin/users/edit/{id}
    controller: App\Controller\admin\AdminController::editUser
    requirements:
        id: '\d+'
show-all-activity:
    path: /admin/all-activity
    controller: App\Controller\admin\AdminController::showActivity
show-user:
    path: /admin/users/{id}/profile
    controller: App\Controller\admin\AdminController::showUser
    requirements:
        id: '\d+'
delete-comment:
    path: /admin/comment/{id}/delete
    controller: App\Controller\admin\AdminController::deleteComment
    requirements:
        id: '\d+'
