register:
    path: /register
    controller: App\Controller\RegistrationController::register
login:
    path: /login
    controller: App\Controller\security\SecurityController::login
logout:
    path: /logout
show-profile:
    path: /user/profile
    controller: App\Controller\user\UserController::showProfile
edit-profile:
    path: /user/profile/edit
    controller: App\Controller\user\UserController::editProfile
change-password:
    path: /user/profile/change-password
    controller: App\Controller\user\UserController::changePassword
show-activity:
    path: /user/activity
    controller: App\Controller\user\UserController::showActivity
show-user-reservations:
    path: /user/reservations
    controller: App\Controller\user\UserController::showReservations
check-active-reservations:
    path: /user/reservations/check
    controller: App\Controller\user\UserController::checkActiveReservations
index:
    path: /
    controller: App\Controller\DefaultController::index
show-catalog:
    path: /catalog/books/{page}
    controller: App\Controller\catalog\CatalogController::showCatalog
    defaults:
        page: 1
    requirements:
        page: '\d+'
show-books-by-author:
    path: /catalog/books-by-author/{slug}/{page}
    controller: App\Controller\catalog\CatalogController::showAuthorCatalog
    defaults:
        page: 1
    requirements:
        slug: '[a-z-]+'
        page: '\d+'
show-books-by-genre:
    path: /catalog/books-by-genre/{slug}/{page}
    controller: App\Controller\catalog\CatalogController::showGenreCatalog
    defaults:
        page: 1
    requirements:
        slug: '[a-z-]+'
        page: '\d+'
show-book:
    path: /catalog/books/{authorSlug}/{bookSlug}
    controller: App\Controller\catalog\BookController::showBook
    requirements:
        authorSlug: '[a-z-]+'
        bookSlug: '[a-z-]+'
show-author:
    path: /catalog/author/{slug}
    controller: App\Controller\catalog\AuthorController::showAuthor
    requirements:
        slug: '[a-z-]+'
reserve-book:
    path: /catalog/books/{authorSlug}/{bookSlug}/reserve
    controller: App\Controller\reader\LibraryController::reserveBook
    requirements:
        authorSlug: '[a-z-]+'
        bookSlug: '[a-z-]+'
cancel-reservation:
    path: /user/reservations/{id}/cancel
    controller: App\Controller\reader\LibraryController::cancelReservation
    requirements:
        id: '[a-f0-9-]+'
toggle-favorite:
    path: /catalog/books/{authorSlug}/{bookSlug}/toggle-favorite
    controller: App\Controller\user\UserController::toggleFavorite
    requirements:
        authorSlug: '[a-z-]+'
        bookSlug: '[a-z-]+'
new-book:
    path: /catalog/books/new
    controller: App\Controller\librarian\LibraryController::newBook
edit-book:
    path: /catalog/{authorSlug}/{bookSlug}/edit
    controller: App\Controller\librarian\LibraryController::editBook
    requirements:
        authorSlug: '[a-z-]+'
        bookSlug: '[a-z-]+'
delete-book:
    path: /catalog/{authorSlug}/{bookSlug}/delete
    controller: App\Controller\librarian\LibraryController::deleteBook
    requirements:
        authorSlug: '[a-z-]+'
        bookSlug: '[a-z-]+'
new-author:
    path: /catalog/authors/new
    controller: App\Controller\librarian\LibraryController::newAuthor
edit-author:
    path: /catalog/{authorSlug}/edit
    controller: App\Controller\librarian\LibraryController::editAuthor
    requirements:
        authorSlug: '[a-z-]+'
delete-author:
    path: /catalog/{slug}/delete
    controller: App\Controller\librarian\LibraryController::deleteAuthor
    requirements:
        slug: '[a-z-]+'
new-genre:
    path: /catalog/genres/new
    controller: App\Controller\librarian\LibraryController::newGenre
show-reservations:
    path: /reservations
    controller: App\Controller\librarian\LibraryController::showReservations
update-reservation:
    path: /reservations/update/{id}/{status}
    controller: App\Controller\librarian\LibraryController::updateReservationStatus
    methods: [GET]
    defaults:
        id: 1
        status: 'reserved'
    requirements:
        id: '[a-f0-9-]+'
show-readers:
    path: /readers
    controller: App\Controller\librarian\LibraryController::showReaders
show-users:
    path: /admin/users
    controller: App\Controller\admin\AdminController::showAllUsers
delete-user:
    path: /admin/users/{id}/delete
    controller: App\Controller\admin\AdminController::deleteUser
    requirements:
        id: '[a-f0-9-]+'
edit-user:
    path: /admin/users/edit/{id}
    controller: App\Controller\admin\AdminController::editUser
    requirements:
        id: '[a-f0-9-]+'
show-all-activity:
    path: /admin/all-activity
    controller: App\Controller\admin\AdminController::showActivity
show-user:
    path: /admin/users/{id}/profile
    controller: App\Controller\admin\AdminController::showUser
    requirements:
        id: '[a-f0-9-]+'
delete-comment:
    path: /admin/comment/{id}/delete
    controller: App\Controller\admin\AdminController::deleteComment
    requirements:
        id: '[a-f0-9-]+'
