# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    app.user_photo_dir: '%kernel.project_dir%/public/uploads/photos'
    app.book_cover_dir: '%kernel.project_dir%/public/uploads/covers'
    app.author_portrait_dir: '%kernel.project_dir%/public/uploads/portraits'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: false      # Automatically injects dependencies in your services.
        autoconfigure: false # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\user\UserController:
        tags: ['controller.service_arguments']
        arguments:
            - '@app.user_manager'
            - '@security.token_storage'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    app.user_manager:
        class: App\Service\UserManager
        arguments:
            - '@doctrine'
            - '@app.file_manager'
            - '@app.password_manager'
            - '%app.user_photo_dir%'

    app.file_manager:
        class: App\Service\FileManager

    app.password_manager:
        class: App\Service\PasswordManager
        arguments:
            - '@security.user_password_encoder.generic'
